### ISSUE TITLE
Doesn't work on some roms

### ISSUE THREAD

**Issue by tearfulDalvik** [rubensousa/FloatingToolbar#8] opened 2016-05-02 14:50 UTC
RT

**Comment by rubensousa** [comment] 2016-05-02 15:47
What do you mean by RT?

**Comment by tearfulDalvik** [comment] 2016-05-03 04:31
Whatever,It doesn't work on LG G5,Nubia Z9 max,Sony Z5p etc

**Comment by rubensousa** [comment] 2016-05-03 15:40
What exactly doesn't work? It would help if you could describe the issue or
even provide a screenshot or recording.

**Comment by tearfulDalvik** [comment] 2016-05-03 23:16
Just no response after pressing the fab.

**Comment by tearfulDalvik** [comment] 2016-05-03 23:20
Sorry I can't record , It works well on my device , it is my user reported that to me.

**Comment by rubensousa** [comment] 2016-05-04 13:22
Can you send the sample code of your FloatingToolbar setup? Are you setting another click listener to the FAB?

**Comment by tearfulDalvik** [comment] 2016-05-04 14:39
Thanks for your patient ! But I didn't set any other listener to the fab.

**Comment by rubensousa** [comment] 2016-05-04 14:49
If there's no response after pressing the FAB, it could be because:
- Animations aren't starting for some weird reason. What I could do is force the start with .start() of the ViewPropertyAnimator, but I don't know if this would still fix it.
- FAB is not attached to the FloatingToolbar.

Please, copy a sample of your layout and java code so I can try to reproduce this.

**Comment by tearfulDalvik** [comment] 2016-05-04 14:52
Sure.But I can't get touch with programmer this time. How about Friday?

**Comment by rubensousa** [comment] 2016-05-04 14:54
Just post it here when you can. I'll take a look when I have time.

**Comment by tearfulDalvik** [comment] 2016-05-04 14:59
Yes,thank you very much.

**Comment by tearfulDalvik** [comment] 2016-05-06 09:18
Hi, these are my code:

```
@Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);
        setContentView(R.layout.main);
        ArrayList<Map<String,String[]>> al = new ArrayList<>();
        final Map<String,String[]> map_main = new HashMap<>();
        map_main.put(SQLHelper.TABLE,new String[]{"password"});
        map_main.put(SQLHelper.FIELD,new String[]{"name","host","user","pw","time"});
        al.add(map_main);
        sql = new SQLHelper(this,"passwords",al,0);
        getSupportActionBar().setSubtitle(getString(R.string.passwords));

        if (sql.select().getCount() > 0)
        {
            findViewById(R.id.mainLinearLayout).setVisibility(View.GONE);
            rv = (RecyclerView) findViewById(R.id.main_rv);
            final FloatingToolbar ftb = (FloatingToolbar) findViewById(R.id.floatingToolbar);
            assert rv != null;
            rv.setVisibility(View.VISIBLE);
            rv.setLayoutManager(new LinearLayoutManager(this));
            rv.setAdapter(new PasswordAdapter(sql.select()));
            rv.addItemDecoration(new RecyclerView.ItemDecoration(){
                    @Override
                    public void getItemOffsets(Rect rect, int position, RecyclerView rv)
                    {
                        //rect.bottom += 10;
                    }
                });
            rv.setOnScrollListener(new RecyclerView.OnScrollListener(){
                    @Override
                    public void onScrolled(RecyclerView rv, int p1, int p2)
                    {
                        if (p1 < p2)
                        {
                            ((FloatingActionButton) findViewById(R.id.fab)).hide();
                        }
                        else
                        {
                            ((FloatingActionButton) findViewById(R.id.fab)).show();
                        }
                    }
                });
            rv.setOnTouchListener(new View.OnTouchListener() {
                @Override
                public boolean onTouch(View v, MotionEvent event) {
                    ftb.hide();
                    return false;
                }
            });
            rv.addOnItemTouchListener(new RecyclerView.OnItemTouchListener() {
                @Override
                public boolean onInterceptTouchEvent(RecyclerView rv, MotionEvent e) {
                    ftb.hide();
                    return false;
                }

                @Override
                public void onTouchEvent(RecyclerView rv, MotionEvent e) {
                    ftb.hide();
                }

                @Override
                public void onRequestDisallowInterceptTouchEvent(boolean disallowIntercept) {
                }
            });
            ftb.attachFab((FloatingActionButton) findViewById(R.id.fab));
            ftb.setClickListener(new FloatingToolbar.ItemClickListener() {
                Toast toast;
                @Override
                public void onItemClick(MenuItem menuItem) {
                    switch(menuItem.getItemId()){
                        case R.id.generater:
                            showNewPassword();
                            break;

                        case R.id.instert:
                            insert(null);
                            break;
                    }
                }

                @Override
                public void onItemLongClick(MenuItem menuItem) {
                    if(toast != null) toast.cancel();
                    (toast = Toast.makeText(MainApplication.getApplication(),menuItem.getTitle(),Toast.LENGTH_LONG)).show();
                }
            });
        }
    }
```

**Comment by tearfulDalvik** [comment] 2016-05-06 09:40
And this is the xml file:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <RelativeLayout
        android:layout_height="match_parent"
        android:layout_width="match_parent">

        <android.support.v7.widget.RecyclerView
            android:layout_width="match_parent"
            android:visibility="gone"
            android:layout_height="match_parent"
            android:id="@+id/main_rv"/>

        <LinearLayout
            android:layout_width="match_parent"
            android:id="@+id/mainLinearLayout"
            android:gravity="center"
            android:orientation="vertical"
            android:layout_height="match_parent">

            <TextView
                android:layout_height="wrap_content"
                android:layout_width="wrap_content"
                android:text="..."
                android:textAppearance="?android:attr/textAppearanceLarge"
                android:paddingBottom="5dp"/>

            <TextView
                android:layout_height="wrap_content"
                android:layout_width="wrap_content"
                android:text="..."
                android:textAppearance="?android:attr/textAppearanceMedium"
                android:paddingBottom="5dp"/>

            <Button
                android:layout_height="wrap_content"
                android:layout_width="wrap_content"
                android:onClick="how"
                android:text="..."/>

        </LinearLayout>

    </RelativeLayout>

    <com.github.rubensousa.floatingtoolbar.FloatingToolbar
        android:id="@+id/floatingToolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_gravity="bottom"
        app:floatingMenu="@menu/menu_bar" />

    <android.support.design.widget.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="20dp"
        android:layout_gravity="end|bottom"
        android:id="@+id/fab"
        android:src="@drawable/ic_expand_more_white_24dp"
        android:layout_marginBottom="20dp"/>

</android.support.design.widget.CoordinatorLayout>
```

**Comment by rubensousa** [comment] 2016-05-07 12:01
Why did you close this? Did you fix something?

**Comment by tearfulDalvik** [comment] 2016-05-07 13:55
Oh god. I wanted to comment but clicked close...
Yes I think I fixed it. Sorry to touble you, it is my fault.
But there is still a problem, which is the restored FAB's position.

**Comment by rubensousa** [comment] 2016-05-07 13:57
Is it the same as [issue 6](https://github.com/rubensousa/FloatingToolbar/issues/6)?

**Comment by tearfulDalvik** [comment] 2016-05-09 01:47
Yes. But the different is my incorrect position is center left.

**Comment by rubensousa** [comment] 2016-06-11 12:22
Did you fix this or just gave up using the library? I haven't been able to reproduce this with your layout.

**Comment by tearfulDalvik** [comment] 2016-06-14 11:24
Well I'm still using it and I'm looking at issue 6, It u can't reproduce it , this may help you:
[screenshot](https://dl.ifengge.cn/?file=IMG_20160614_192035.jpg&down=0)

**Comment by rubensousa** [comment] 2016-06-14 12:58
Ok, I'll take a look at this again. But I'll close this issue in favor of #6

**Closed as completed by rubensousa** 2016-06-14 12:58 UTC
Labels: Needs info
