### ISSUE TITLE
FAB moving to incorrect location.

### ISSUE THREAD

**Issue by christianjgreen** [rubensousa/FloatingToolbar#6] opened 2016-04-29 14:43 UTC
Initially, the FAB is in the correct location within the layout. One the FAB is pressed, the animation takes it to the opposite corner (Top left) where it continues to stay.

API Level: 23

**Comment by rubensousa** [comment] 2016-04-29 15:18
Can you check if it's still happening in 0.3? I can't reproduce this.

**Comment by christianjgreen** [comment] 2016-04-29 16:23
Issue fixed with newest released!
Thanks Ruben :)

**Comment by christianjgreen** [comment] 2016-04-29 17:24
Hey Ruben,

It seemed fixed, but now the issue is back. The button is leaving the
screen to the top left corner. I'll keep testing and get some more details.

On Fri, Apr 29, 2016 at 11:18 AM, Rúben Sousa notifications@github.com
wrote:

> Can you check if it's still happening in 0.3? I can't reproduce this.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rubensousa/FloatingToolbar/issues/6#issuecomment-215751335

## 

Christian Green
Zamination.com LLC
Mobile Developer

**Comment by rubensousa** [comment] 2016-04-29 17:26
Ok. If you can, please upload a video that demos the issue.

**Comment by christianjgreen** [comment] 2016-04-29 18:13
Have not been able to reproduce, but I'll stay in touch!

Thanks for your hard work!

Christain

On Fri, Apr 29, 2016 at 1:26 PM, Rúben Sousa notifications@github.com
wrote:

> Ok. If you can, please upload a video that demos the issue.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rubensousa/FloatingToolbar/issues/6#issuecomment-215822503

## 

Christian Green
Zamination.com LLC
Mobile Developer

**Comment by christianjgreen** [comment] 2016-04-29 21:02
Here's an example. It's the same issue as before, but I limited the size of
the coordinated layout so instead of going offscreen it stays on screen

On Fri, Apr 29, 2016 at 2:13 PM, Christian Green <
christian.j.green@gmail.com> wrote:

> Have not been able to reproduce, but I'll stay in touch!
> 
> Thanks for your hard work!
> 
> Christain
> 
> On Fri, Apr 29, 2016 at 1:26 PM, Rúben Sousa notifications@github.com
> wrote:
> 
> > Ok. If you can, please upload a video that demos the issue.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/rubensousa/FloatingToolbar/issues/6#issuecomment-215822503
> 
> ## 
> 
> Christian Green
> Zamination.com LLC
> Mobile Developer

## 

Christian Green
Zamination.com LLC
Mobile Developer

**Comment by rubensousa** [comment] 2016-06-11 12:20
This seemed like an issue causing by the layout you were using. Did you fix this or just gave up on using it?

**Comment by rubensousa** [comment] 2016-06-29 19:40
Should be fixed by #14
Will be out in 0.4

**Closed as completed by rubensousa** 2016-06-29 19:40 UTC
Labels: help wanted, Needs info
